runtime: python311

entrypoint: uvicorn main:api --host 0.0.0.0 --port $PORT

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1

handlers:
  - url: /.*
    script: auto